title: "Maciej Buczak"
description: "Risk Management & Research Management management"
baseurl: ""
url: ""
permalink: /:title/

# Włączamy obsługę Sass
sass:
  sass_dir: assets/css
  style: compressed
